# -*- coding: utf-8 -*-
"""report_gen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16FVEuFQhp_2JURlnqtOXpsc23_Gpra6g
"""

pip install fpdf pandas matplotlib

"""
CODTECH IT SOLUTIONS - INTERNSHIP TASK 2
PROJECT: AUTOMATED REPORT GENERATION (FIXED ENCODING)
INTERN: Sumedha
ID: CTIS8362
"""

import pandas as pd
import matplotlib.pyplot as plt
from fpdf import FPDF
import datetime
import os

# ==========================================
# 1. DATA PREPARATION
# ==========================================
def create_sample_csv():
    """Generates a sample sales dataset for the report."""
    data = {
        'Product': ['Laptops', 'Mobiles', 'Tablets', 'Monitors', 'Keyboards', 'Mice'],
        'Units_Sold': [50, 120, 80, 60, 200, 150],
        'Unit_Price': [1000, 600, 400, 300, 50, 30],
        'Revenue': [50000, 72000, 32000, 18000, 10000, 4500]
    }
    df = pd.DataFrame(data)
    df.to_csv("sales_data.csv", index=False)
    print("Step 1: Data file 'sales_data.csv' prepared.")

# ==========================================
# 2. PDF REPORT GENERATOR CLASS
# ==========================================
class PDFReport(FPDF):
    def header(self):
        """Creates a consistent header for every page."""
        self.set_font('Arial', 'B', 20)
        self.set_text_color(44, 62, 80) # Corporate Dark Blue
        self.cell(0, 15, 'MONTHLY SALES PERFORMANCE REPORT', 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 5, f'Generated on: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 1, 'C')
        self.ln(10)

    def footer(self):
        """Adds page numbers at the bottom of every page."""
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

    def chapter_title(self, title):
        """Formats section headings with a background color."""
        self.set_font('Arial', 'B', 14)
        self.set_fill_color(200, 220, 255) # Light Blue Background
        self.set_text_color(0, 0, 0)
        self.cell(0, 10, title, 0, 1, 'L', 1)
        self.ln(5)

    def create_table(self, df):
        """Generates a formatted table from a DataFrame."""
        self.set_font('Arial', 'B', 12)
        self.set_fill_color(44, 62, 80)
        self.set_text_color(255, 255, 255)

        w = 47
        for col in df.columns:
            self.cell(w, 10, col, 1, 0, 'C', 1)
        self.ln()

        self.set_font('Arial', '', 12)
        self.set_text_color(0, 0, 0)
        for _, row in df.iterrows():
            self.cell(w, 10, str(row['Product']), 1)
            self.cell(w, 10, str(row['Units_Sold']), 1, 0, 'C')
            self.cell(w, 10, f"${row['Unit_Price']:,}", 1, 0, 'R')
            self.cell(w, 10, f"${row['Revenue']:,}", 1, 0, 'R')
            self.ln()

# ==========================================
# 3. ANALYSIS & AUTOMATION ENGINE
# ==========================================
def generate_automated_report():
    # Load and Analyze Data
    if not os.path.exists("sales_data.csv"):
        create_sample_csv()

    df = pd.read_csv("sales_data.csv")
    total_revenue = df['Revenue'].sum()
    avg_sales = df['Units_Sold'].mean()
    top_product = df.loc[df['Revenue'].idxmax(), 'Product']

    # --- Step A: Create Visualization ---
    plt.figure(figsize=(10, 6))
    plt.bar(df['Product'], df['Revenue'], color='#3498db', edgecolor='#2980b9')
    plt.title('Total Revenue by Product Category', fontsize=14)
    plt.ylabel('Revenue in USD ($)')
    plt.grid(axis='y', linestyle='--', alpha=0.7)
    plt.savefig("sales_chart.png", dpi=300)
    plt.close()

    # --- Step B: Build PDF ---
    pdf = PDFReport()
    pdf.add_page()

    # Section 1: Business Summary
    # (Note: Bullet point replaced with '-' to avoid UnicodeEncodeError)
    pdf.chapter_title("1. Business Executive Summary")
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 10, f"- Total Revenue Generated: ${total_revenue:,}", 0, 1)
    pdf.cell(0, 10, f"- Average Units Sold per Category: {avg_sales:.2f}", 0, 1)
    pdf.cell(0, 10, f"- Top Performing Product: {top_product}", 0, 1)
    pdf.ln(10)

    # Section 2: Data Table
    pdf.chapter_title("2. Detailed Inventory Sales Data")
    pdf.create_table(df)
    pdf.ln(15)

    # --- SMART LAYOUT LOGIC ---
    # We check the Y position. If we are too low on the page,
    # we move to a new page to keep the heading and chart together.
    if pdf.get_y() > 150:
        print("Adding page break to keep Chart and Heading together...")
        pdf.add_page()

    # Section 3: Visualization
    pdf.chapter_title("3. Revenue Distribution Chart")
    pdf.image("sales_chart.png", x=10, w=190)

    # Output the File
    try:
        pdf.output("Sales_Analysis_Report_Final.pdf")
        print("\n" + "="*50)
        print("SUCCESS: Professional PDF Report generated!")
        print("Filename: Sales_Analysis_Report_Final.pdf")
        print("="*50)
    except Exception as e:
        print(f"Error saving PDF: {e}")

if __name__ == "__main__":
    generate_automated_report()