# -*- coding: utf-8 -*-
"""weather_script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P5lHbHyrktaxsp4rDs0PaWO_hZNgbGZe
"""

pip install requests pandas matplotlib seaborn

import requests
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime
import logging
import sys

# --- PROFESSIONAL LOGGING SETUP ---
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[logging.StreamHandler(sys.stdout)]
)

class WeatherAnalytics:
    """
    A Professional tool to fetch, process, and visualize 5-day weather forecast data.
    """
    def __init__(self, api_key, city):
        self.api_key = api_key
        self.city = city
        self.base_url = "http://api.openweathermap.org/data/2.5/forecast"
        self.df = None

    def fetch_data(self):
        """Fetches raw 5-day forecast data from OpenWeatherMap API."""
        logging.info(f"Connecting to OpenWeatherMap API for city: {self.city}...")
        params = {
            'q': self.city,
            'appid': self.api_key,
            'units': 'metric'
        }

        try:
            response = requests.get(self.base_url, params=params, timeout=10)
            response.raise_for_status() # Raise error for bad status codes
            data = response.json()
            logging.info("Successfully retrieved data from API.")
            return data
        except requests.exceptions.RequestException as e:
            logging.error(f"API Connection Failed: {e}")
            return None

    def process_data(self, raw_data):
        """Cleans and structures the JSON data into a Pandas DataFrame."""
        logging.info("Processing and cleaning weather data...")
        try:
            weather_list = []
            for item in raw_data['list']:
                weather_list.append({
                    'Timestamp': item['dt_txt'],
                    'Temp': item['main']['temp'],
                    'Feels Like': item['main']['feels_like'],
                    'Humidity': item['main']['humidity'],
                    'Wind Speed': item['wind']['speed'],
                    'Condition': item['weather'][0]['main'],
                    'Description': item['weather'][0]['description']
                })

            self.df = pd.DataFrame(weather_list)
            self.df['Timestamp'] = pd.to_datetime(self.df['Timestamp'])

            # Export raw data to CSV for documentation
            self.df.to_csv(f"{self.city}_weather_data.csv", index=False)
            logging.info(f"Data processed. Shape: {self.df.shape}. Exported to CSV.")
            return True
        except Exception as e:
            logging.error(f"Data Processing Error: {e}")
            return False

    def create_visualizations(self):
        """Generates a professional 4-panel dashboard."""
        if self.df is None:
            logging.error("No data available to visualize.")
            return

        logging.info("Generating visualization dashboard...")

        # Set Global Aesthetics
        sns.set_theme(style="darkgrid")
        plt.rcParams['font.family'] = 'sans-serif'

        fig, axes = plt.subplots(2, 2, figsize=(18, 12))
        fig.suptitle(f"WEATHER ANALYTICS REPORT: {self.city.upper()}\n(5-Day / 3-Hour Forecast)",
                     fontsize=24, fontweight='bold', color='#2c3e50')

        # --- PLOT 1: TEMPERATURE TRENDS ---
        sns.lineplot(ax=axes[0, 0], data=self.df, x='Timestamp', y='Temp',
                     label='Actual Temp', color='#e74c3c', lw=3, marker='o')
        sns.lineplot(ax=axes[0, 0], data=self.df, x='Timestamp', y='Feels Like',
                     label='Feels Like', color='#3498db', linestyle='--', alpha=0.7)
        axes[0, 0].set_title("Temperature Analysis (°C)", fontsize=16, fontweight='semibold')
        axes[0, 0].set_ylabel("Degrees Celsius")
        axes[0, 0].legend()

        # --- PLOT 2: HUMIDITY LEVELS (Area Plot) ---
        axes[0, 1].fill_between(self.df['Timestamp'], self.df['Humidity'], color="#1abc9c", alpha=0.3)
        axes[0, 1].plot(self.df['Timestamp'], self.df['Humidity'], color="#16a085", lw=2)
        axes[0, 1].set_title("Humidity Saturation (%)", fontsize=16, fontweight='semibold')
        axes[0, 1].set_ylabel("Humidity Percentage")

        # --- PLOT 3: WEATHER CONDITION DISTRIBUTION (Pie Chart) ---
        condition_counts = self.df['Condition'].value_counts()
        axes[1, 0].pie(condition_counts, labels=condition_counts.index, autopct='%1.1f%%',
                       startangle=140, colors=sns.color_palette("viridis", len(condition_counts)))
        axes[1, 0].set_title("Atmospheric Condition Distribution", fontsize=16, fontweight='semibold')

        # --- PLOT 4: WIND SPEED VARIATION (Bar Plot) ---
        # Take a subset for clarity (first 15 entries)
        sns.barplot(ax=axes[1, 1], data=self.df.head(15), x='Timestamp', y='Wind Speed',
                    palette="magma")
        axes[1, 1].set_title("Wind Speed Dynamics (Next 45 Hours)", fontsize=16, fontweight='semibold')
        axes[1, 1].set_xticklabels(axes[1, 1].get_xticklabels(), rotation=45, horizontalalignment='right')
        axes[1, 1].set_ylabel("Speed (m/s)")

        # Final Formatting
        plt.tight_layout(rect=[0, 0.03, 1, 0.95])

        # Save high-quality output
        output_file = f"{self.city}_weather_dashboard.png"
        plt.savefig(output_file, dpi=300)
        logging.info(f"Dashboard rendered and saved as {output_file}")
        plt.show()

# --- MAIN EXECUTION BLOCK ---
if __name__ == "__main__":
    # INSTRUCTIONS:
    # 1. Replace 'YOUR_API_KEY' with your actual key from OpenWeatherMap
    # 2. Change 'CITY_NAME' to any city you want to analyze

    API_KEY = "ebaaa1832b4898dbc5e9ea5f1262d7dc"
    CITY_NAME = "Nellore"

    if API_KEY != "ebaaa1832b4898dbc5e9ea5f1262d7dc":
        print("CRITICAL ERROR: Please provide a valid OpenWeatherMap API Key in the script.")
    else:
        # Initialize and Run the application
        app = WeatherAnalytics(API_KEY, CITY_NAME)

        raw_weather_data = app.fetch_data()
        if raw_weather_data:
            success = app.process_data(raw_weather_data)
            if success:
                app.create_visualizations()
                print("\n" + "="*50)
                print("TASK COMPLETED SUCCESSFULLY!")
                print(f"Check folder for {CITY_NAME}_weather_data.csv and the dashboard image.")
                print("="*50)